spring:
  application:
    name: PropertyManagementApplication
  jpa:
    hibernate:
      ddl-auto: "create-drop"
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8082


